### ISSUE TITLE
Pesterchum will not open

### ISSUE THREAD

**Issue by fallibleGod** [illuminatedwax/pesterchum#120]
I had had Pesterchum installed and downloaded for less than 30 minutes when i closed out of it, and it would not open again.
I did the debugging, correctly I don't know, but here is the log I could find.

Qt: Untested Windows version 6.2 detected!
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 104, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 362, in **init**
IOError: [Errno 2] No such file or directory: u'C:\Users\Nicholas\AppData\Local\pesterchum/profiles/faliableGod.js'

**Comment by illuminatedwax** [comment]
Can you email me at dranger@gmail.com so I can send you a file to fix
things?
