### ISSUE TITLE
Program seems to be unwilling to open.

### ISSUE THREAD

**Issue by Tenebrous-Guile** [illuminatedwax/pesterchum#122]
I recently, after having to turn this laptop on and off (it turned itself off apparently) following an internet outage and having to use a mobile hotspot for my internet, found that pesterchum was unwilling to function.  I would click on it and I'd get a loading cursor for a few seconds and task manager showed the app starting, but then it closed out with nary so much as a yellow window.    

I ran the debug and here's what I got.

=== PESTERCHUM DEBUG 08-21-14 13-36 ===
Qt: Untested Windows version 6.2 detected!
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 101, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 267, in load
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 307, in loads
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 322, in decode
ValueError: Extra data: line 1 column 483 - line 1 column 504 (char 483 - 504)
=== PESTERCHUM DEBUG 08-21-14 13-36 ===
Qt: Untested Windows version 6.2 detected!
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 101, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 267, in load
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 307, in loads
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 322, in decode
ValueError: Extra data: line 1 column 483 - line 1 column 504 (char 483 - 504)
=== PESTERCHUM DEBUG 08-21-14 13-37 ===
Qt: Untested Windows version 6.2 detected!
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 101, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 267, in load
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 307, in loads
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 322, in decode
ValueError: Extra data: line 1 column 483 - line 1 column 504 (char 483 - 504)
=== PESTERCHUM DEBUG 08-21-14 13-37 ===
Qt: Untested Windows version 6.2 detected!
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 101, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 267, in load
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 307, in loads
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 322, in decode
ValueError: Extra data: line 1 column 483 - line 1 column 504 (char 483 - 504)
=== PESTERCHUM DEBUG 08-21-14 14-09 ===
Qt: Untested Windows version 6.2 detected!
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 101, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 267, in load
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 307, in loads
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 322, in decode
ValueError: Extra data: line 1 column 483 - line 1 column 504 (char 483 - 504)

**Comment by illuminatedwax** [comment]
Looks like your pesterchum.js is corrupted. Can you post the contents of
that file here?

(To find it: Search for %LOCALAPPDATA%, click the Local folder, then the
pesterchum folder, and it should be in there. You can open it in Notepad.)

**Comment by Tenebrous-Guile** [comment]
Searching that term gave me nothing, I'm running windows 8 if that helps.
