### ISSUE TITLE
My Pesterchum Won't Open

### ISSUE THREAD

**Issue by Persanon** [illuminatedwax/pesterchum#133]
So, I started using pesterchum for a while a while back, stopped, then when I decided to start using it again, it wouldn't open.  I've had this problem for a while, now, and just now decided to look up a solution.  I apologize in advance if I say anything that may seem stupid, I'm net exactly computer savvy...

**Comment by arcaneAgilmente** [comment]
Run the degugger, paste the log to pastebin and then link it here.

**Comment by Persanon** [comment]
I can't run it.

**Comment by Persanon** [comment]
I tried, but it wouldn't work.

**Comment by Persanon** [comment]
Is there some other way I can fix it?  Or maybe there's a certain way I'm supposed to do the debugging?

**Comment by illuminatedwax** [comment]
How did you install it, and what happens when it doesn't work?

**Comment by illuminatedwax** [comment]
(I should add that it won't actually FIX the problem, but it WILL create a
"debug.log" (or just "debug") file that you can then copy & paste here;
that will help diagnose the issue.)

**Comment by Persanon** [comment]
Well, I installed it from the forum thread, again, and when I try to open it, nothing happens.  And the same goes for the debugger.  Nothing happens.

**Comment by illuminatedwax** [comment]
Check for the existence of the debug.log file. It's very possible that it
DID in fact run, but immediately crashed -- if the debugger worked, it will
have left a debug trace in that file. Try looking in the C:\Pesterchum
directory for something called "debug.log" or just "debug".

**Comment by Persanon** [comment]
How do I get to the C:\Pesterchum directory?

**Comment by illuminatedwax** [comment]
Not sure what operating system you're using, but if you browse your files,
and go to your main hard drive (should be called C:), you should see a
folder called Pesterchum.

**Comment by Persanon** [comment]
I found the folder, but couldn't find it.  I tried running the debugger again, but I still couldn't find it.

**Comment by Persanon** [comment]
Oh, and whenever I try running the debugger, this window pops up:

Error loading Python DLL: python26.dll (error code 126)

**Comment by illuminatedwax** [comment]
Ah! That's the error I was worried about. When you install the debugger,
make sure you _copy_ the debugger file into the C:\Pesterchum directory.
(Right-click-drag the file from wherever it is to the Pesterchum folder,
and then when it asks, select Copy.)

**Comment by Persanon** [comment]
Do I copy the Debbuger or pesterchum.debug.exe.manifest?  Or the whole folder?

**Comment by illuminatedwax** [comment]
Copy the debugger from where you downloaded it into the Pesterchum folder.

**Comment by Persanon** [comment]
Okay, now what?

**Comment by illuminatedwax** [comment]
You should be able to run the debugger without the message appearing. When
it runs, you'll have to open the debug.log file and copy/paste its contents
here.

**Comment by Persanon** [comment]
=== PESTERCHUM DEBUG 11-15-14 22-19 ===
Registered quirks: upper(), lower(), scraRegistered quirks: Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 1132, in **init**
  File "<string>", line 1424, in changeProfile
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/menus", line 800, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 338, in availableProfiles
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 363, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 267, in load
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 307, in loads
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 319, in decode
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 338, in raw_decode
ValueError: No JSON object could be decoded
eError: No JSON object could be decoded
=== PESTERCHUM DEBUG 11-15-14 22-20 ===
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 1132, in **init**
  File "<string>", line 1424, in changeProfile
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/menus", line 800, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 338, in availableProfiles
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 363, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 267, in load
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 307, in loads
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 319, in decode
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 338, in raw_decode
ValueError: No JSON object could be decoded

**Comment by Persanon** [comment]
Is this right?

**Comment by illuminatedwax** [comment]
Yup! It looks like one of your configuration files went bad. Email me at
dranger@gmail.com with this same text because I'll need to have you send me
files and github doesn't do attachments.

**Comment by Persanon** [comment]
Alright, I sent a message.

**Comment by Persanon** [comment]
I'd be the ShiningShadows8 guy.

**Comment by irkedIsaac** [comment]
Just ran into this same problem after reinstalling pesterchum. 

EDIT: I fixed it.

**Comment by Persanon** [comment]
Fixed Pesterchum?  How?

**Comment by irkedIsaac** [comment]
AppData > Local > pesterchum

Grab any pesterlogs, chumhandles, and what have you from the files there and then delete what remains. The application is trying — and, ultimately, failing — to use outdated data. If memory serves, there's also some conversion thing on the thread, but this is less irritating.

**Comment by Persanon** [comment]
Well, I did that, and it still won't work.
