### ISSUE TITLE
Updated code won't open on linux

### ISSUE THREAD

**Issue by rimbaum** [illuminatedwax/pesterchum#134]
I did a git pull to get the most recent code updates, and it left my pesterchum unable to open. I ran it in a terminal to see what was going on, and this is the log I got:

becca@skaianet:~/.pesterchum$ python pesterchum.py
Traceback (most recent call last):
  File "pesterchum.py", line 5, in <module>
    import version
  File "/home/becca/.pesterchum/version.py", line 1, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request

**Comment by illuminatedwax** [comment]
The new codebase is migrating to python3. Try python3 pesterchum.py

**Comment by rimbaum** [comment]
Different error this time.

becca@skaianet:~/.pesterchum$ python3 pesterchum.py
ERROR: The following modules are required for Pesterchum to run and are missing on your system:
- 'PyQt5'

This is despite me installing the packages python-pyqt5 and pyqt5-dev on debian.

**Comment by illuminatedwax** [comment]
It's possible that it didn't install PyQt5 for _Python 3_ -- I'm not sure
if there's a debian package specifically for that, but since you have
pyqt5-dev installed, I _think_ you'll be able to install PyQt5 for Python 3
manually.

**Comment by rimbaum** [comment]
Okay, so after fiddling around, the debian packages required to run the new code are:

python3-pyqt5.qtmultimedia
python3-pyqt5

EDIT: Confirmed that these two packages and their dependencies will get the new code working on both debian and ubuntu, along with the "python3 pesterchum.py" command.
