### ISSUE TITLE
Im having trouble identifying a problem

### ISSUE THREAD

**Issue by Sagethemage** [illuminatedwax/pesterchum#137]
Well, this is seemingly a common problem among many Pesterchum users; Pesterchum (which I have un-installed and re-installed more than enough times) has failed to open on more than one occasion, and ceases to load up. I highly believe that this has something to do with a corrupted file, but I'm not quite sure what file that is. I've deleted every trace of Pesterchum on my computer and re-installed it, the zip version and all; I've done this about 3-4 times until I just kept the normal version on my computer. 

I took the liberty of using the debugger and this is what I got:

IOError: [Errno 2] No such file or directory: u'C:\Users\stephanie\AppData\Local\pesterchum/profiles/remedialArmageddons.js'
=== PESTERCHUM DEBUG 11-25-14 21-14 ===
Qt: Untested Windows version 6.2 detected!
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 104, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 362, in **init**
IOError: [Errno 2] No such file or directory: u'C:\Users\stephanie\AppData\Local\pesterchum/profiles/remedialArmageddons.js'

What do I do from this point onwards? 

Oh, and my Pesterchum.js:

 {"emptyGroups": false, "hideOfflineChums": false, "tabmemos": true, "time12Format": true, "showSeconds": false, "sortMethod": 0, "lastUCheck": 1403995974, "traymsg": false, "soundon": true, "defaultprofile": "remedialArmageddons", "showTimeStamps": true, "chums": ["gallantCryptographer", "andrewHussie"], "onlineNumbers": false, "block": []}

I'm not really sure if there is something wrong with my main profile, or if it's just some other problem I cannot identify; like with coding and such. Could someone contact me privately about this or give me some guidence?

**Comment by illuminatedwax** [comment]
You can alter pesterchum.js to this and it should fix it:

{"emptyGroups": false, "hideOfflineChums": false, "tabmemos": true,
"time12Format": true, "showSeconds": false, "sortMethod": 0, "lastUCheck":
1403995974, "traymsg": false, "soundon": true, "showTimeStamps": true,
"chums": ["gallantCryptographer", "andrewHussie"], "onlineNumbers": false,
"block": []}
