### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by electrofox** [illuminatedwax/pesterchum#139]
Please help,i'm having issues with Pesterchum. I can't pester,the chat window won't open when i hit Pester! button. I really want to use Pesterchum.

**Comment by arcaneAgilmente** [comment]
run the debugger, encounter the problem and post the debug log back here.

**Comment by electrofox** [comment]
=== PESTERCHUM DEBUG 07-08-15 17-48 ===
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2417, in profileSelected
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 440, in newUserProfile
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 45: ordinal not in range(128)
Object::connect: No such slot PesterWindow::modesUpdated(QString,QString)
Object::connect:  (receiver name: 'main')
INFO:root:connecting to irc.mindfang.org:6667
INFO:root:---> send "NICK pesterClient213"
INFO:root:---> send "USER pcc31 irc.mindfang.org irc.mindfang.org pcc31"
INFO:root:---> recv "NOTICE irc5.mindfang.or :**\* Looking up your hostname..."
INFO:root:---> recv "NOTICE irc5.mindfang.or :**\* Couldn't resolve your hostname; using your IP address instead"
INFO:root:---> send "PONG A0BD62F0"
INFO:root:---> send "JOIN #pesterchum"
INFO:root:---> send "PRIVMSG #pesterchum :MOOD >0"
INFO:root:---> recv "JOIN pesterClient213: #pesterchum"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 29 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 30 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 24 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 15 names"
INFO:root:---> send "PRIVMSG #pesterchum :GETMOOD arachnidsGrip"
INFO:root:---> recv "PRIVMSG arachnidsGrip :MOOD >14"
INFO:root:---> recv "PRIVMSG grimmRapier :MOOD >3"
INFO:root:---> recv "PRIVMSG grimmRapier :MOOD >4"
Traceback (most recent call last):
  File "<string>", line 1645, in pesterSelectedChum
  File "<string>", line 1653, in newConversationWindow
  File "<string>", line 1329, in newConversation
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/convo", line 574, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 55, in log
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 45: ordinal not in range(128)
INFO:root:---> recv "PRIVMSG grimmRapier :MOOD >5"
Traceback (most recent call last):
  File "<string>", line 1645, in pesterSelectedChum
  File "<string>", line 1653, in newConversationWindow
  File "<string>", line 1329, in newConversation
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/convo", line 574, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 67, in log
KeyError: 'text'
Traceback (most recent call last):
  File "<string>", line 1645, in pesterSelectedChum
  File "<string>", line 1653, in newConversationWindow
  File "<string>", line 1329, in newConversation
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/convo", line 574, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 67, in log
KeyError: 'text'
INFO:root:---> recv "PRIVMSG pesterClient257 :MOOD >0"
INFO:root:---> recv "PRIVMSG grimmRapier :MOOD >6"
INFO:root:---> recv "QUIT poppiedPlayer: Ping timeout"
INFO:root:---> recv "PRIVMSG pesterClient257 :MOOD >0"
INFO:root:---> recv "PRIVMSG grimmRapier :MOOD >0"
INFO:root:---> recv "QUIT jawBite: Connection reset by peer"
INFO:root:---> recv "PRIVMSG poppiedPlayer :MOOD >0"
INFO:root:---> recv "JOIN pesterClient594: #pesterchum"
INFO:root:---> recv "PRIVMSG pesterClient594 :MOOD >0"
INFO:root:---> recv "PRIVMSG pesterClient594 :GETMOOD elusiveOwltwinArmageddonectoBiologisttwinArmageddons"
INFO:root:---> recv "PRIVMSG twinArmageddons :MOOD >11"
INFO:root:---> recv "PRIVMSG twinArmageddon :MOOD >11"
INFO:root:---> recv "PRIVMSG ectoBiologist :MOOD >5"
INFO:root:---> recv "PRIVMSG elusiveOwl :MOOD >3"
INFO:root:---> recv "JOIN crossedGreaser: #pesterchum"
INFO:root:---> recv "PRIVMSG crossedGreaser :MOOD >9"
INFO:root:---> recv "PRIVMSG pesterClient594 :MOOD >0"
INFO:root:---> recv "PRIVMSG jawBite :MOOD >0"
INFO:root:---> send "NAMES #pesterchum"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 29 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 30 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 24 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 15 names"
INFO:root:---> recv "PRIVMSG crossedGreaser :MOOD >2"
INFO:root:---> recv "JOIN navyNekomimi: #pesterchum"
INFO:root:---> recv "PRIVMSG navyNekomimi :MOOD >0"
INFO:root:---> recv "PRIVMSG navyNekomimi :GETMOOD voidsWrathlimitedExplosionsinsaneQuestioneernavyNekomimiinsaneQuestioneermobile"
INFO:root:---> recv "PRIVMSG insaneQuestioneer :MOOD >18"
INFO:root:---> recv "PRIVMSG voidsWrath :MOOD >16"
INFO:root:---> recv "PRIVMSG limitedExplosions :MOOD >4"
INFO:root:---> recv "JOIN pesterClient729: #pesterchum"
INFO:root:---> recv "PRIVMSG pesterClient729 :MOOD >0"
INFO:root:---> recv "PRIVMSG insaneQuestioneermobile :MOOD >0"
INFO:root:---> recv "QUIT pesterClient729: Connection reset by peer"
INFO:root:---> recv "PRIVMSG navyNekomimi :MOOD >0"
INFO:root:---> recv "PRIVMSG monoBlitz :MOOD >0"
BEGIN NOTIFY
Traceback (most recent call last):
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/convo", line 191, in changeTab
KeyError: u'arachnidsGrip'
Traceback (most recent call last):
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/convo", line 113, in closeEvent
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/convo", line 180, in tabClose
KeyError: u'arachnidsGrip'
=== PESTERCHUM DEBUG 07-08-15 17-49 ===
=== PESTERCHUM DEBUG 07-08-15 17-51 ===
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2417, in profileSelected
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 440, in newUserProfile
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 45: ordinal not in range(128)
Object::connect: No such slot PesterWindow::modesUpdated(QString,QString)
Object::connect:  (receiver name: 'main')
INFO:root:connecting to irc.mindfang.org:6667
INFO:root:---> send "NICK pesterClient209"
INFO:root:---> send "USER pcc31 irc.mindfang.org irc.mindfang.org pcc31"
INFO:root:---> recv "NOTICE irc5.mindfang.or :**\* Looking up your hostname..."
INFO:root:---> recv "NOTICE irc5.mindfang.or :**\* Couldn't resolve your hostname; using your IP address instead"
INFO:root:---> send "PONG E5C9409"
INFO:root:---> send "JOIN #pesterchum"
INFO:root:---> send "PRIVMSG #pesterchum :MOOD >0"
INFO:root:---> recv "JOIN pesterClient209: #pesterchum"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 24 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 29 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 29 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 29 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 28 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 25 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 27 names"
INFO:root:---> recv "NAMES #pesterchum: 26 names"
INFO:root:---> recv "NAMES #pesterchum: 18 names"
INFO:root:---> send "PRIVMSG #pesterchum :GETMOOD arachnidsGrip"
INFO:root:---> recv "JOIN unanimousTwin1: #pesterchum"
INFO:root:---> recv "PRIVMSG unanimousTwin1 :MOOD >6"
INFO:root:---> recv "PRIVMSG arachnidsGrip :MOOD >14"
INFO:root:---> recv "PRIVMSG unanimousTwin1 :GETMOOD nervousAnarchisttwinAnarchist"
INFO:root:---> recv "PRIVMSG pesterClient163 :MOOD >0"
INFO:root:---> recv "PRIVMSG pesterClient163 :MOOD >0"
INFO:root:---> recv "PRIVMSG pesterClient763 :MOOD >0"
Could not parse stylesheet of widget 0x1fa43f8
INFO:root:---> recv "PRIVMSG pesterClient763 :MOOD >0"
INFO:root:---> recv "PRIVMSG pesterClient763 :MOOD >0"
INFO:root:---> recv "PRIVMSG forevermoreFaithful :MOOD >0"
INFO:root:---> recv "PRIVMSG pesterClient631 :MOOD >0"
INFO:root:---> recv "JOIN purpleAnthea: #pesterchum"
INFO:root:---> recv "PRIVMSG purpleAnthea :MOOD >0"
INFO:root:---> recv "PRIVMSG zorraroastedCoffie :MOOD >16"
INFO:root:---> recv "PRIVMSG pesterClient631 :MOOD >0"
INFO:root:---> recv "PRIVMSG pesterClient631 :MOOD >0"
INFO:root:---> recv "QUIT deceitfulArtist: Connection reset by peer"
INFO:root:---> recv "PRIVMSG pesterClient977 :MOOD >0"
INFO:root:---> recv "JOIN horribleCompanion: #pesterchum"

**Comment by ghost** [comment]
Go here for help: http://www.mspaforums.com/showthread.php?58047-PESTERCHUM-3-41-Meet-the-new-thread-same-as-the-old-thread%21-%28Upd8-mod-apps-on-pg2%29

**Comment by electrofox** [comment]
i cannot find any answers for my question. please help i really wanna use it!

**Comment by ghost** [comment]
This place is pretty much a ghost town. For actual help and responses, go to the forum thread: http://mspaforums.com/showthread.php?58047-PESTERCHUM-3-41-Meet-the-new-thread-same-as-the-old-thread%21-%28Upd8-mod-apps-on-pg2%29
