### ISSUE TITLE
./pesterchum doesn't work

### ISSUE THREAD

**Issue by ghost** [illuminatedwax/pesterchum#214]
I downloaded the file unzipped it and put it in my Documents folder. I installed python-qt4 and python-pygame, and then opened the folder in terminal (essentially like using the `cd` command but without the hassle) and then typed `./pesterchum` and got this error:

`~/Documents/pesterchum-master$ ./pesterchum 
Traceback (most recent call last):
  File "pesterchum.py", line 5, in <module>
    import version
  File "/home/hershey/Documents/pesterchum-master/version.py", line 1, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request`

so I tried the `make` command:

`~/Documents/pesterchum-master$ make
Ready to install...`

then I did `make install` and got this:

`make install
mkdir -p /usr/local/bin
mkdir -p /usr/local/lib/pesterchum
mkdir: cannot create directory ‘/usr/local/lib/pesterchum’: Permission denied
Makefile:14: recipe for target 'make-install-dirs' failed
make: *** [make-install-dirs] Error 1`

Please help me.

**Comment by monabat79** [comment]
From what I assume, you are probably using a Linux operating system (probably Ubuntu?). Correct me if I am wrong.

It wants you to [run the command as the root user](https://unix.stackexchange.com/questions/3063/how-do-i-run-a-command-as-the-system-administrator-root#3064).

If you are on Windows however, simply run `cmd` (or your preferred command line program) as Admin and try again.

**Comment by ghost** [comment]
You are right I'm on Ubuntu (sorry I didn't specify)
So I tried `sudo make` and it gave me the same result so I assumed it worked, so I try `sudo make install` and I got this:
`~/Documents/pesterchum-master$ sudo make installmkdir -p /usr/local/bin
mkdir -p /usr/local/lib/pesterchum
mkdir -p /usr/local/lib/pesterchum/libs
mkdir -p /usr/local/lib/pesterchum/oyoyo
mkdir -p /usr/local/lib/pesterchum/quirks
mkdir -p /usr/local/lib/pesterchum/smilies
mkdir -p /usr/local/lib/pesterchum/themes
install -m 644 *.py /usr/local/lib/pesterchum
install -m 644 libs/*.py /usr/local/lib/pesterchum/libs
install -m 644 oyoyo/*.py /usr/local/lib/pesterchum/oyoyo
install -m 644 quirks/*.py /usr/local/lib/pesterchum/quirks
install -m 644 smilies/* /usr/local/lib/pesterchum/smilies
cp -r themes/* /usr/local/lib/pesterchum/themes
chmod +x /usr/local/bin/pesterchum`
I assumed it was it ok and tried `./pesterchum` and got the same error:
`~/Documents/pesterchum-master$ ./pesterchum
Traceback (most recent call last):
  File "pesterchum.py", line 5, in <module>
    import version
  File "/home/hershey/Documents/pesterchum-master/version.py", line 1, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request`
Is `sudo make install` asking me to install the quirks, themes, and then take ownership of the file? I assume not but I'm no expert.

**Comment by bebis** [comment]
I'm sorry if I'm resurrecting this one a from the dead, but I'm having the same exact issue on Manjaro
