### ISSUE TITLE
Refusing to open-

### ISSUE THREAD

**Issue by strik** [illuminatedwax/pesterchum#31]
I ran the debug log to see if I could possibly figure out the issue- my computer had unexpectedly shut down as the program was open and when I turned it back on Pesterchum refused to work. I have uninstalled and re-installed it to no avail. This is the log, can anyone help me? I've tried running it with different compatibility modes and as an administrator, but I'm not computer savvy enough to fix it alone.

=== PESTERCHUM DEBUG 04-11-12 19-32 ===
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 101, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 267, in load
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 307, in loads
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 319, in decode
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 338, in raw_decode
ValueError: No JSON object could be decoded

**Comment by TheBasementNerd** [comment]
im having this exact same problem. there was a power outage while pesterchum was up and now nothing is working.

im not familiar with this, but my best guess is that something failed to load

**Comment by SweetDevilZira** [comment]
I have the exact same problem! I tried to uninstall and reinstall and it didn't work! I'm freaking out man.
