### ISSUE TITLE
old and corrupt profile files...

### ISSUE THREAD

**Issue by ghost** [illuminatedwax/pesterchum#84]
debug log:

---

=== PESTERCHUM DEBUG 07-14-13 09-29 ===
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 104, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 362, in **init**
IOError: [Errno 2] No such file or directory: u'C:\Users\Owner\AppData\Local\pesterchum/profiles/monochusRenascence.js'

---

the files for the profile were accidentally deleted a few months ago, so they're irretrievable u_u; can someone help please? thank you in advance ~~

**Comment by arcaneAgilmente** [comment]
Locate your local app data folder, find the pesterchum folder (that's inside localappdata) and AFTER COPYING IT SOMEWHERE SAFE delete it. Pesterchum should open again.
