### ISSUE TITLE
Pesterchum will not launch

### ISSUE THREAD

**Issue by technicalRenegade** [illuminatedwax/pesterchum#95]
I am running on a Windows computer and using the unzipped version of pesterchum. The program has run and worked fine for weeks, but suddenly it has decided it wont run anymore. I have deleted and re-installed pesterchum more than once, but to no avail.

**Comment by illuminatedwax** [comment]
Your profile or config files are probably corrupted. Are any of your
profile files blank? If you run the debugger, it should help us determine
which ones.

**Comment by technicalRenegade** [comment]
I am not really sure how to interpret this information, but here is the debug.log I received after an attempt at debugging. 
=== PESTERCHUM DEBUG 11-08-13 15-02 ===
Registered quirks: upper(), lower(), scramble(), reverse()
Traceback (most recent call last):
  File "<string>", line 2912, in <module>
  File "<string>", line 2604, in **init**
  File "<string>", line 937, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/profile", line 101, in **init**
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 267, in load
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json", line 307, in loads
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 319, in decode
  File "c:\Users\Stephen\Documents\projects\build\build\pyi.win32\pesterchum\outPYZ1.pyz/json.decoder", line 338, in raw_decode
ValueError: No JSON object could be decoded

**Comment by technicalRenegade** [comment]
I'm not sure if you got a notification from when I commented on the problem, but in case you did not I am letting you know that I posted the debug log I retrieved after running the debug file.

**Comment by illuminatedwax** [comment]
Oh my god I'm so behind on my email. Are you still having trouble? If so:

Can you go to %LOCALAPPDATA% (if you don't know how to get there, just go
to Start->Search and type it in, a Local folder should pop up) then go to
pesterchum and send me the pesterchum.js file?
